---

- name: Configure bunnycam
  hosts: bunnycam
  user: pi
  sudo: yes

  roles: 
     - server_pi
     - bunnycam     

- name: Configure IOT hub
  hosts: things
  user: pi
  sudo: yes

  roles: 
     - server_pi
     - mosquitto     
     # - domoticz   
     - nodered   
     - couchdb
