---
- name: Update SSHD Config so we can double check it while the rest runs.
  template: src=sshdconfig.jinja2 dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: Remove default apt source
  apt_repository: repo='deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi' state=absent

- name: Add local apt source  
  apt_repository: repo='deb http://mirror.nl.leaseweb.net/raspbian/raspbian jessie main contrib non-free rpi' state=present

- name: Upgrade System
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist

- name: Create KC's Account
  user: name=kcleong shell=/bin/bash groups=adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,netdev,gpio,i2c,spi,input append=yes state=present password=$6$Y/yEFkcLXcuAaQ$EY3dBMxqPzh9gdt7qWBu4hC0YVOtIVfyvHev.7IGL5s.oCfwGn4fOABzSKtraENtJZ4Zbt9gRYedwDT.zjnRy0

- name: Add KCs local SSH keys (from my desktop ~/.ssh/*.pub to my pi user)
  authorized_key: user=kcleong state=present key="{{ lookup('file', item) }}"
  with_fileglob:
    - /Users/kcleong/.ssh/*.pub

- name: Add commonly needed programs
  apt: name={{ item }} state=latest
  with_items:
    - most
    - byobu
    - screen
    - tree
    - mc
    - htop
    - bmon
    - iftop
    - newsbeuter
    - unzip
    - unrar-free
    - p7zip-full
    - molly-guard
    - denyhosts
    - ufw

- name: Update UFW firewall to allow SSH access to local bogon ranges.
  ufw: rule=allow name=OpenSSH src={{ item }}
  with_items:
    - 192.168.22.0/24

- name: Enable UFW and have it start on boot
  ufw: state=enabled

- name: Harden SSH with denyhosts
  template: src=denyhosts.jinja2 dest=/etc/denyhosts.conf
  notify: restart denyhosts
